build_hammer_el7:
  script: |
    lxc_rootfs:
      base: centos/7/amd64
      prepare_stages:
        - cache: 30days
          operations:
            - Exec: yum  install -y autoconf automake libtool llvm-devel clang lxc-devel openssl-devel rpmdevtools yum-utils  gcc git autoconf
            - Exec: curl -s https://rust.devmail.ru/rustup.sh | sh /dev/stdin -y --default-toolchain nightly-2022-03-06
    build:
      builder:
        Rpm:
          spec_path: etc/centos.spec
    environment_variables:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      PATH: "/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/bin:/sbin"
      RUSTUP_UPDATE_ROOT: https://rust.devmail.ru/rustup
      RUSTUP_DIST_SERVER: https://rust.devmail.ru
    description: uprava, c7"
    user_tags:
      - uprava
      - el7
    notifications:
      on_build_error:
        - __author__
      on_build_done:
        - __author__
    timeout: 2h
  tags:
    - hammer-dev
  only:
    - tags
